name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Summon
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🙏
        
        Before submitting, please check if a similar issue already exists.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen instead.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce this behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A clear description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running Summon on?
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Summon Version
      description: What version of Summon are you using?
      placeholder: e.g., 0.0.1
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Application Logs
      description: |
        Please include relevant application logs. You can find your logs by:
        1. Opening Summon
        2. Going to Help menu → "Open Log Folder"
        3. Copy and paste relevant log entries here
        
        **Important**: Please review logs for any sensitive information before sharing.
      placeholder: Paste relevant log entries here...
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Any additional information that might help us understand the issue better.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues that might be related to this bug
          required: true
        - label: I have reviewed the logs for any sensitive information before sharing
          required: true
