name: ✨ Feature Request
description: Suggest a new feature or enhancement for Summon
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        Please check if a similar feature request already exists before submitting.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of Summon would this feature affect?
      options:
        - MCP Server Generation
        - OpenAPI Integration
        - AI Playground
        - Tool Management
        - External MCP Servers
        - User Interface
        - Authentication/Security
        - Performance
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help you or others.
      placeholder: This would help me/users to...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request here.
      placeholder: Any additional information that might help us understand your request better.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests that might be similar
          required: true
        - label: This feature would benefit other users, not just my specific use case
          required: true
